### PR TITLE
Fix ask for location modal opening always

### PR DESCRIPTION
**Pull request by johan-t**
## Describe the issue:
Even when the location has already been set the fallback option would open. This was due to Safari not changing the state of the permission API like other browsers did. So when we were checking after the 15 seconds timer if the permission is still at 'prompt', we initalized it to 'prompt', kind of like Schrödingers cat. This caused `watchPosition` to fail and set the `position` to `null` for 1 second, during this 1 second the check for `openAskForLocation` would fail as the position was now at `null`.

## Explain how you solved the issue:
I added a `boolean` that checks if the `position` has been set before and required this to be `false` in order to trigger the `openAskForLocation` function in the case of the permission still being 'prompt' after 15 seconds.

That way we worked around the permission state not changing in Safari.
## Additional notes or considerations:
Due to us not being able to capture when the state changes to denied we are not able to instantly open the ask for location modal after blocking the location on Safari. The modal will open only after 15 seconds on Safari.

### CODE REVIEW

**Comment by johan-t** [comment]
> @johan-t found a fix, take a look at watchposition and test it out on safari. 
> 
> 
> 
> 
> 
> btw, when you refresh the page a lot of the times and either allow or disallow, but don't remember the decision, then safari will not ask anymore. just open the page in a new tab

Good Idea, but do you know how stable watch position is? Maybe a cool down would be better because this would also trigger if it randomly fails for 1 second. If watch position is super stable this is a great approach but if it fails regularly we need some kind of cool-down

**Comment by brandesdavid** [comment]
> > > @johan-t found a fix, take a look at watchposition and test it out on safari.
> > > btw, when you refresh the page a lot of the times and either allow or disallow, but don't remember the decision, then safari will not ask anymore. just open the page in a new tab
> > 
> > 
> > Good Idea, but do you know how stable watch position is? Maybe a cool down would be better because this would also trigger if it randomly fails for 1 second. If watch position is super stable this is a great approach but if it fails regularly we need some kind of cool-down
> 
> You can surely add a small timeout, but watch position is stable enough. if it fails for a second, that should still be okay IMO.

@johan-t 

i have added maximum age and timeout to make it even more stable. The user position should be set with a time distance/maximum age of 15 seconds, in the case of not getting the position, because a user may be underground etc. and also, the maximum amount of time for the device to send the location is 15 seconds. After these 15 seconds, the modal will popup, because the website cannot fetch the location.

**Comment by johan-t** [comment]
> > > > @johan-t found a fix, take a look at watchposition and test it out on safari.
> > > > btw, when you refresh the page a lot of the times and either allow or disallow, but don't remember the decision, then safari will not ask anymore. just open the page in a new tab
> > > 
> > > 
> > > Good Idea, but do you know how stable watch position is? Maybe a cool down would be better because this would also trigger if it randomly fails for 1 second. If watch position is super stable this is a great approach but if it fails regularly we need some kind of cool-down
> > 
> > 
> > You can surely add a small timeout, but watch position is stable enough. if it fails for a second, that should still be okay IMO.
> 
> @johan-t
> 
> i have added maximum age and timeout to make it even more stable. The user position should be set with a time distance/maximum age of 15 seconds, in the case of not getting the position, because a user may be underground etc. and also, the maximum amount of time for the device to send the location is 15 seconds. After these 15 seconds, the modal will popup, because the website cannot fetch the location.

But if we also have a 15 seconds cool-down is it not the same as bevor where we were having the issue with safari?

**Comment by johan-t** [comment]
@brandesdavid Can you test this out with the vercel preview if it is stable in the Ubahn etc?

**Comment by brandesdavid** [comment]
> @brandesdavid Can you test this out with the vercel preview if it is stable in the Ubahn etc?

will test later.

> > > > > @johan-t found a fix, take a look at watchposition and test it out on safari.
> > > > > btw, when you refresh the page a lot of the times and either allow or disallow, but don't remember the decision, then safari will not ask anymore. just open the page in a new tab
> > > > 
> > > > 
> > > > Good Idea, but do you know how stable watch position is? Maybe a cool down would be better because this would also trigger if it randomly fails for 1 second. If watch position is super stable this is a great approach but if it fails regularly we need some kind of cool-down
> > > 
> > > 
> > > You can surely add a small timeout, but watch position is stable enough. if it fails for a second, that should still be okay IMO.
> > 
> > 
> > @johan-t
> > i have added maximum age and timeout to make it even more stable. The user position should be set with a time distance/maximum age of 15 seconds, in the case of not getting the position, because a user may be underground etc. and also, the maximum amount of time for the device to send the location is 15 seconds. After these 15 seconds, the modal will popup, because the website cannot fetch the location.
> 
> But if we also have a 15 seconds cool-down is it not the same as bevor where we were having the issue with safari?

no not really, the device will show the last 15 seconds of location maximumAGe and with a timeout of 15 seconds. if we don't receive it anymore, after 15 seconds then call askforlocation. this means we will always have a location, even if your internet connections breaks off a bit, but if it breaks off longer than 15 seconds, the ask for location should be on

**Comment by brandesdavid** [comment]
@johan-t but i will test it later

**Pull request merged**
